import os 

# This script creates fcl files to process dm events generated by BdNMC + evgen.exe 

directory = r'./hepevt_ouputs'
counter = 0 
n_events = 0 
for filename in os.listdir(directory):
    outputname = './fcl_2nd_half/proddm_common_uboone_'+str(counter)+'.fcl'
    out_f = open(outputname,'a')
    with open("./hepevt_ouputs/"+filename) as f:

       mylist = list(f)
       print("./hepevt_ouputs/"+filename)
       print('Number of lines ', len(mylist))
       print('Number of events ', len(mylist)/5)
       print('\n')
       out_f.writelines(['#include "proddm_common_uboone.fcl" ', '\n','\n'])
       out_f.writelines(['physics.producers.generator.InputFileName:"../hepevt_ouputs/'+filename+'"', '\n'])
       out_f.writelines(['source.maxEvents:'+str(len(mylist)/5),'\n', 'source.firstRun:' + str(counter)])
       out_f.close()
       n_events += len(mylist)/5
    counter+=1

print('Total number of events :', n_events)